# Generated by Django 3.2.9 on 2021-12-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacherstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
